### ISSUE TITLE
Mark this Repo as a Template

### ISSUE THREAD

**Issue by MinerSebas** [trailofbits/dylint-template#4]
This Repo should be marked as a Template: [https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository)

**Comment by smoelius** [comment]
That's a good idea!

Thanks!
